const object1 = {};  
const a = Symbol('a');  
const b = Symbol.for('b');  
object1[a] = 'localSymbol';  
object1[b] = 'globalSymbol';  
const object2 = {};  
const c = Symbol('c');  
object2[c] = 'Carry';  
const objectSymbols = Object.getOwnPropertySymbols(object1);  
console.log(objectSymbols.length);